# Generated by Django 5.1.2 on 2024-10-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
