# Generated by Django 5.1.6 on 2025-04-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_noti_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="strikes",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("github", "GitHub"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
