# Generated by Django 5.1.6 on 2025-04-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_user_is_noti_on_user_strikes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_fa",
            field=models.BooleanField(default=True),
        ),
    ]
