# Generated by Django 5.1.6 on 2025-04-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0003_user_bio_user_two_fa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="two_fa",
            new_name="is_two_fa",
        ),
    ]
