# Generated by Django 5.1.6 on 2025-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0004_rename_two_fa_user_is_two_fa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
