# Generated by Django 5.1.6 on 2025-04-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
