# Generated by Django 5.1.6 on 2025-04-20 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username cannot contain spaces",
                        regex="^\\S+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=6,
                        message="Username must be at least 6 characters long",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=255,
                        message="Username cannot be longer than 255 characters",
                    ),
                ],
            ),
        ),
    ]
