# Generated by Django 5.1.6 on 2025-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
