# Generated by Django 5.1.6 on 2025-04-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0011_blog_category_user_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="cat_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="overview",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="report_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="visibility",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Blog_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core_db.blog"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_db.category",
                    ),
                ),
            ],
        ),
    ]
