# Generated by Django 5.1.6 on 2025-04-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0013_alter_blog_author_alter_blog_content_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user_category",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="unique_user_category"
            ),
        ),
    ]
