# Generated by Django 5.1.6 on 2025-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0014_user_category_unique_user_category"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="blog_category",
            constraint=models.UniqueConstraint(
                fields=("blog", "category"), name="unique_blog_category"
            ),
        ),
    ]
