# Generated by Django 5.1.6 on 2025-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0015_blog_category_unique_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["-score"], name="core_db_blo_score_4cbf3b_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["-created_at"], name="core_db_blo_created_efc5c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["status", "visibility", "-score"],
                name="core_db_blo_status_dc48ac_idx",
            ),
        ),
    ]
